[[module]]
route = "/example2-ping"
module = "./target/wasm32-wasi/debug/example2.wasm" 

[[module]]
route = "/example3"
module = "./target/wasm32-wasi/debug/example3.wasm" 

[[module]]
route = "/example4/..."
module = "./target/wasm32-wasi/debug/example4.wasm"
volumes = {"/" = "./target/wasm32-wasi/debug/example4.wasm"}

[[module]]
route = "/static/..."
module = "./fileserver.gr.wasm"
volumes = {"/" = "/Users/michaelneuhold/Development/repos.nosync/wasm-server-side/_static"}